//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.11 at 03:31:33 PM CST 
//


package draft.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the draft.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetDraft_QNAME = new QName("", "get-draft");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: draft.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DraftType }
     * 
     */
    public DraftType createDraftType() {
        return new DraftType();
    }

    /**
     * Create an instance of {@link RequestListType }
     * 
     */
    public RequestListType createRequestListType() {
        return new RequestListType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link PeriodType }
     * 
     */
    public PeriodType createPeriodType() {
        return new PeriodType();
    }

    /**
     * Create an instance of {@link ItemlistType }
     * 
     */
    public ItemlistType createItemlistType() {
        return new ItemlistType();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link AReportType }
     * 
     */
    public AReportType createAReportType() {
        return new AReportType();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DraftType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "get-draft")
    public JAXBElement<DraftType> createGetDraft(DraftType value) {
        return new JAXBElement<DraftType>(_GetDraft_QNAME, DraftType.class, null, value);
    }

}
